// Exercise seed data for FitTrack Pro MVP
// Covers all muscle groups and equipment types

import type { NewExercise } from '../schema';

export const exerciseSeedData: NewExercise[] = [
  // ============= BODYWEIGHT EXERCISES =============
  {
    id: 'push-ups',
    name: 'Push-ups',
    description: 'Classic upper body exercise targeting chest, shoulders, and triceps.',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: '1. Start in a plank position with hands shoulder-width apart.\n2. Lower your body until chest nearly touches the floor.\n3. Push back up to starting position.\n4. Keep core engaged throughout.',
  },
  {
    id: 'pull-ups',
    name: 'Pull-ups',
    description: 'Fundamental upper body pulling exercise for back and biceps.',
    muscleGroups: ['back', 'biceps'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    instructions: '1. Hang from a bar with an overhand grip, arms fully extended.\n2. Pull yourself up until chin clears the bar.\n3. Lower back down with control.\n4. Avoid swinging or kipping.',
  },
  {
    id: 'squats',
    name: 'Bodyweight Squats',
    description: 'Lower body exercise targeting quadriceps, glutes, and hamstrings.',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: '1. Stand with feet shoulder-width apart.\n2. Lower your body as if sitting in a chair.\n3. Keep chest up and knees behind toes.\n4. Push through heels to return to standing.',
  },
  {
    id: 'lunges',
    name: 'Lunges',
    description: 'Unilateral leg exercise for quadriceps, glutes, and hamstrings.',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: '1. Step forward with one leg.\n2. Lower hips until both knees are at 90 degrees.\n3. Keep front knee behind front toe.\n4. Push back to starting position and switch legs.',
  },
  {
    id: 'plank',
    name: 'Plank',
    description: 'Isometric core exercise for building stability and endurance.',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: '1. Start in a forearm plank position.\n2. Keep body in a straight line from head to heels.\n3. Engage core and glutes.\n4. Hold for desired duration.',
  },
  {
    id: 'burpees',
    name: 'Burpees',
    description: 'Full-body explosive exercise combining squat, push-up, and jump.',
    muscleGroups: ['quadriceps', 'glutes', 'chest', 'core'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    instructions: '1. Start standing, then drop into a squat position.\n2. Place hands on ground and jump feet back to plank.\n3. Do a push-up.\n4. Jump feet back to hands and explode up.\n5. Land softly and repeat.',
  },
  {
    id: 'dips',
    name: 'Dips',
    description: 'Upper body pushing exercise for triceps and chest.',
    muscleGroups: ['triceps', 'chest', 'shoulders'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    instructions: '1. Grip parallel bars or use a bench behind you.\n2. Lower your body by bending elbows.\n3. Keep elbows close to body.\n4. Push back up to starting position.',
  },
  {
    id: 'mountain-climbers',
    name: 'Mountain Climbers',
    description: 'Dynamic core exercise that also raises heart rate.',
    muscleGroups: ['core', 'shoulders'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: '1. Start in a high plank position.\n2. Drive one knee toward chest.\n3. Quickly switch legs.\n4. Maintain a flat back and rapid pace.',
  },
  {
    id: 'glute-bridges',
    name: 'Glute Bridges',
    description: 'Isolation exercise for glutes and hamstrings.',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: '1. Lie on back with knees bent, feet flat.\n2. Lift hips toward ceiling.\n3. Squeeze glutes at the top.\n4. Lower back down with control.',
  },
  {
    id: 'calf-raises',
    name: 'Calf Raises',
    description: 'Isolation exercise for calf muscles.',
    muscleGroups: ['calves'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: '1. Stand on edge of a step or on flat ground.\n2. Rise up onto toes.\n3. Pause at the top.\n4. Lower heels below step level if possible.',
  },
  {
    id: 'crunches',
    name: 'Crunches',
    description: 'Classic abdominal isolation exercise.',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: '1. Lie on back with knees bent, hands behind head.\n2. Lift shoulders off ground by contracting abs.\n3. Keep lower back pressed to floor.\n4. Lower with control.',
  },
  {
    id: 'leg-raises',
    name: 'Leg Raises',
    description: 'Lower abdominal exercise for core strength.',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    instructions: '1. Lie flat on back with hands under lower back.\n2. Lift legs up until perpendicular to ground.\n3. Lower legs slowly without touching ground.\n4. Keep lower back pressed to floor.',
  },
  {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    description: 'Full-body cardio warm-up exercise.',
    muscleGroups: ['quadriceps', 'calves', 'shoulders'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: '1. Start standing with feet together, arms at sides.\n2. Jump feet apart while raising arms overhead.\n3. Jump back to starting position.\n4. Maintain a steady rhythm.',
  },

  // ============= DUMBBELL EXERCISES =============
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    description: 'Chest exercise allowing for greater range of motion than barbell.',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'dumbbells',
    difficulty: 'beginner',
    instructions: '1. Lie on bench holding dumbbells at chest level.\n2. Press weights up until arms are extended.\n3. Lower weights with control to starting position.\n4. Keep elbows at 45-degree angle.',
  },
  {
    id: 'dumbbell-rows',
    name: 'Dumbbell Rows',
    description: 'Unilateral back exercise for thickness and strength.',
    muscleGroups: ['back', 'biceps'],
    equipment: 'dumbbells',
    difficulty: 'beginner',
    instructions: '1. Place one hand and knee on a bench.\n2. Hold dumbbell in other hand, arm hanging straight.\n3. Pull dumbbell up toward hip.\n4. Lower with control, squeeze back at top.',
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    description: 'Overhead pressing exercise for shoulder development.',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'dumbbells',
    difficulty: 'intermediate',
    instructions: '1. Sit or stand with dumbbells at shoulder height.\n2. Press weights overhead until arms are extended.\n3. Lower with control to starting position.\n4. Avoid arching back.',
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    description: 'Isolation exercise for side deltoids.',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbells',
    difficulty: 'beginner',
    instructions: '1. Stand with dumbbells at sides.\n2. Raise arms out to sides until shoulder height.\n3. Keep slight bend in elbows.\n4. Lower with control.',
  },
  {
    id: 'dumbbell-bicep-curls',
    name: 'Dumbbell Bicep Curls',
    description: 'Classic arm isolation exercise for biceps.',
    muscleGroups: ['biceps'],
    equipment: 'dumbbells',
    difficulty: 'beginner',
    instructions: '1. Stand holding dumbbells at sides, palms facing forward.\n2. Curl weights toward shoulders.\n3. Keep elbows stationary.\n4. Lower with control.',
  },
  {
    id: 'dumbbell-tricep-extension',
    name: 'Dumbbell Tricep Extension',
    description: 'Overhead tricep isolation exercise.',
    muscleGroups: ['triceps'],
    equipment: 'dumbbells',
    difficulty: 'beginner',
    instructions: '1. Hold one dumbbell overhead with both hands.\n2. Lower weight behind head by bending elbows.\n3. Extend arms back overhead.\n4. Keep elbows close to head.',
  },
  {
    id: 'dumbbell-squats',
    name: 'Dumbbell Squats',
    description: 'Weighted squat variation for lower body strength.',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'dumbbells',
    difficulty: 'beginner',
    instructions: '1. Hold dumbbells at shoulders or at sides.\n2. Lower into squat position.\n3. Keep chest up and knees behind toes.\n4. Push through heels to stand.',
  },
  {
    id: 'dumbbell-lunges',
    name: 'Dumbbell Lunges',
    description: 'Weighted unilateral leg exercise.',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'dumbbells',
    difficulty: 'intermediate',
    instructions: '1. Hold dumbbells at sides or on shoulders.\n2. Step forward into lunge position.\n3. Lower until both knees are at 90 degrees.\n4. Push back to start and switch legs.',
  },
  {
    id: 'dumbbell-deadlift',
    name: 'Dumbbell Deadlift',
    description: 'Posterior chain exercise for back, glutes, and hamstrings.',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'dumbbells',
    difficulty: 'intermediate',
    instructions: '1. Stand with feet hip-width, dumbbells in front.\n2. Hinge at hips, lower weights toward floor.\n3. Keep back straight and core engaged.\n4. Drive through heels to stand.',
  },
  {
    id: 'dumbbell-chest-fly',
    name: 'Dumbbell Chest Fly',
    description: 'Isolation exercise for chest muscles.',
    muscleGroups: ['chest'],
    equipment: 'dumbbells',
    difficulty: 'beginner',
    instructions: '1. Lie on bench holding dumbbells above chest.\n2. Lower arms out to sides with slight bend in elbows.\n3. Feel stretch in chest.\n4. Bring weights back together overhead.',
  },
  {
    id: 'dumbbell-shrugs',
    name: 'Dumbbell Shrugs',
    description: 'Trapezius muscle isolation exercise.',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbells',
    difficulty: 'beginner',
    instructions: '1. Hold dumbbells at sides.\n2. Elevate shoulders toward ears.\n3. Hold at top briefly.\n4. Lower with control.',
  },
  {
    id: 'dumbbell-russian-twist',
    name: 'Dumbbell Russian Twist',
    description: 'Rotational core exercise for obliques.',
    muscleGroups: ['core'],
    equipment: 'dumbbells',
    difficulty: 'intermediate',
    instructions: '1. Sit on ground, lean back slightly with knees bent.\n2. Hold dumbbell with both hands at chest.\n3. Rotate torso side to side.\n4. Keep feet off ground for added difficulty.',
  },
  {
    id: 'dumbbell-step-ups',
    name: 'Dumbbell Step-ups',
    description: 'Unilateral leg exercise for functional strength.',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'dumbbells',
    difficulty: 'intermediate',
    instructions: '1. Hold dumbbells at sides.\n2. Step onto box or bench with one foot.\n3. Drive through heel to stand on box.\n4. Step down and switch legs.',
  },
  {
    id: 'dumbbell-wrist-curls',
    name: 'Dumbbell Wrist Curls',
    description: 'Forearm and grip strength exercise.',
    muscleGroups: ['forearms'],
    equipment: 'dumbbells',
    difficulty: 'beginner',
    instructions: '1. Rest forearm on bench with hand off edge.\n2. Hold dumbbell with palm facing up.\n3. Curl wrist up.\n4. Lower with control.',
  },

  // ============= BARBELL EXERCISES =============
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    description: 'Classic chest exercise for building upper body strength.',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'barbells',
    difficulty: 'intermediate',
    instructions: '1. Lie on bench, grip bar slightly wider than shoulders.\n2. Unrack and lower bar to mid-chest.\n3. Press bar back up until arms are extended.\n4. Keep feet flat on floor.',
  },
  {
    id: 'barbell-squat',
    name: 'Barbell Squat',
    description: 'King of lower body exercises for legs and glutes.',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'barbells',
    difficulty: 'advanced',
    instructions: '1. Position bar on upper back, grip wider than shoulders.\n2. Unrack and lower into squat with controlled descent.\n3. Keep chest up and knees tracking over toes.\n4. Drive through heels to stand.',
  },
  {
    id: 'barbell-deadlift',
    name: 'Barbell Deadlift',
    description: 'Total body strength exercise targeting posterior chain.',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'barbells',
    difficulty: 'advanced',
    instructions: '1. Stand with feet hip-width, bar over mid-foot.\n2. Hinge at hips, grip bar just outside legs.\n3. Drive through heels, pull bar up while standing.\n4. Keep bar close to body throughout.',
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    description: 'Compound back exercise for thickness and strength.',
    muscleGroups: ['back', 'biceps'],
    equipment: 'barbells',
    difficulty: 'intermediate',
    instructions: '1. Bend over with flat back, grip bar.\n2. Pull bar to lower chest.\n3. Squeeze shoulder blades together.\n4. Lower with control.',
  },
  {
    id: 'barbell-overhead-press',
    name: 'Barbell Overhead Press',
    description: 'Fundamental shoulder press for overhead strength.',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'barbells',
    difficulty: 'intermediate',
    instructions: '1. Stand holding bar at shoulder height.\n2. Press bar overhead until arms are extended.\n3. Lower bar to starting position.\n4. Avoid excessive back arch.',
  },
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    description: 'Glute and posterior chain exercise.',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: 'barbells',
    difficulty: 'intermediate',
    instructions: '1. Rest upper back on bench, feet planted.\n2. Place bar across hips.\n3. Extend hips fully, squeezing glutes.\n4. Lower with control.',
  },
  {
    id: 'barbell-lunge',
    name: 'Barbell Lunge',
    description: 'Weighted lunge for leg strength and stability.',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'barbells',
    difficulty: 'advanced',
    instructions: '1. Position bar on upper back.\n2. Step forward into lunge.\n3. Lower until back knee nearly touches ground.\n4. Push back to start and alternate legs.',
  },
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    description: 'Bicep exercise allowing for heavy loading.',
    muscleGroups: ['biceps'],
    equipment: 'barbells',
    difficulty: 'beginner',
    instructions: '1. Stand holding bar with shoulder-width grip.\n2. Curl bar toward chest.\n3. Keep elbows stationary.\n4. Lower with control.',
  },
  {
    id: 'barbell-skullcrushers',
    name: 'Barbell Skullcrushers',
    description: 'Tricep isolation exercise lying on bench.',
    muscleGroups: ['triceps'],
    equipment: 'barbells',
    difficulty: 'intermediate',
    instructions: '1. Lie on bench holding bar above chest.\n2. Lower bar toward forehead by bending elbows.\n3. Extend arms back up.\n4. Keep elbows stationary.',
  },
  {
    id: 'barbell-good-mornings',
    name: 'Barbell Good Mornings',
    description: 'Posterior chain exercise for hamstrings and lower back.',
    muscleGroups: ['hamstrings', 'back'],
    equipment: 'barbells',
    difficulty: 'advanced',
    instructions: '1. Position bar on upper back.\n2. Hinge at hips, lowering torso toward ground.\n3. Keep back straight and slight bend in knees.\n4. Return to standing by extending hips.',
  },
  {
    id: 'barbell-shrugs',
    name: 'Barbell Shrugs',
    description: 'Heavy trap exercise for shoulder and neck strength.',
    muscleGroups: ['shoulders'],
    equipment: 'barbells',
    difficulty: 'beginner',
    instructions: '1. Stand holding bar in front of body.\n2. Elevate shoulders toward ears.\n3. Hold briefly at top.\n4. Lower with control.',
  },
  {
    id: 'barbell-front-squat',
    name: 'Barbell Front Squat',
    description: 'Quad-focused squat variation with bar on front shoulders.',
    muscleGroups: ['quadriceps', 'glutes', 'core'],
    equipment: 'barbells',
    difficulty: 'advanced',
    instructions: '1. Rack bar on front shoulders, arms crossed.\n2. Keep elbows high and chest up.\n3. Lower into squat.\n4. Drive through heels to stand.',
  },
  {
    id: 'barbell-romanian-deadlift',
    name: 'Barbell Romanian Deadlift',
    description: 'Hamstring and glute exercise with minimal knee bend.',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    equipment: 'barbells',
    difficulty: 'intermediate',
    instructions: '1. Stand holding bar at hip level.\n2. Hinge at hips, lowering bar toward feet.\n3. Keep legs mostly straight.\n4. Return to standing by squeezing glutes.',
  },

  // ============= KETTLEBELL EXERCISES =============
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    description: 'Explosive hip hinge exercise for power and conditioning.',
    muscleGroups: ['glutes', 'hamstrings', 'core'],
    equipment: 'kettlebells',
    difficulty: 'intermediate',
    instructions: '1. Stand with feet wider than shoulders, holding kettlebell.\n2. Hinge at hips, swinging KB between legs.\n3. explosively extend hips, swinging KB to chest height.\n4. Control descent back to starting position.',
  },
  {
    id: 'kettlebell-goblet-squat',
    name: 'Kettlebell Goblet Squat',
    description: 'Front-loaded squat for leg strength and mobility.',
    muscleGroups: ['quadriceps', 'glutes', 'core'],
    equipment: 'kettlebells',
    difficulty: 'beginner',
    instructions: '1. Hold KB at chest with both hands.\n2. Lower into squat with elbows inside knees.\n3. Keep chest up and weight on heels.\n4. Drive through heels to stand.',
  },
  {
    id: 'kettlebell-clean',
    name: 'Kettlebell Clean',
    description: 'Explosive exercise bringing KB from ground to rack position.',
    muscleGroups: ['back', 'shoulders', 'glutes'],
    equipment: 'kettlebells',
    difficulty: 'advanced',
    instructions: '1. Start with KB between feet.\n2. Hinge and hike KB back between legs.\n3. Explode up, pulling KB toward rack position.\n4. Punch through to catch KB at chest.',
  },
  {
    id: 'kettlebell-snatch',
    name: 'Kettlebell Snatch',
    description: 'Explosive overhead movement for total body power.',
    muscleGroups: ['shoulders', 'back', 'glutes', 'core'],
    equipment: 'kettlebells',
    difficulty: 'advanced',
    instructions: '1. Swing KB between legs in hike position.\n2. Explosively extend hips and pull KB overhead.\n3. Punch hand up to lock out overhead.\n4. Control descent back to start.',
  },
  {
    id: 'kettlebell-turkish-get-up',
    name: 'Kettlebell Turkish Get-up',
    description: 'Complex full-body exercise for stability and strength.',
    muscleGroups: ['core', 'shoulders', 'glutes'],
    equipment: 'kettlebells',
    difficulty: 'advanced',
    instructions: '1. Lie on back holding KB overhead.\n2. Roll to elbow, then hand.\n3. Bridge hips and sweep leg through.\n4. Stand up tall, keeping KB overhead throughout.\n5. Reverse movement to return to start.',
  },
  {
    id: 'kettlebell-press',
    name: 'Kettlebell Press',
    description: 'Overhead press for shoulder strength.',
    muscleGroups: ['shoulders', 'triceps', 'core'],
    equipment: 'kettlebells',
    difficulty: 'intermediate',
    instructions: '1. Clean KB to rack position.\n2. Press KB overhead until arm is extended.\n3. Keep core tight and avoid leaning back.\n4. Lower with control to rack position.',
  },
  {
    id: 'kettlebell-row',
    name: 'Kettlebell Row',
    description: 'Single-arm row exercise for back development.',
    muscleGroups: ['back', 'biceps'],
    equipment: 'kettlebells',
    difficulty: 'beginner',
    instructions: '1. Place one hand on bench, hold KB in other.\n2. Hinge forward with flat back.\n3. Pull KB toward hip.\n4. Lower with control, squeezing back at top.',
  },
  {
    id: 'kettlebell-lunge',
    name: 'Kettlebell Lunge',
    description: 'Weighted lunge variation using kettlebell.',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'kettlebells',
    difficulty: 'intermediate',
    instructions: '1. Hold KB at chest or at sides.\n2. Step forward into lunge.\n3. Lower until both knees are at 90 degrees.\n4. Push back to start and switch legs.',
  },
  {
    id: 'kettlebell-deadlift',
    name: 'Kettlebell Deadlift',
    description: 'Hip hinge exercise for posterior chain strength.',
    muscleGroups: ['glutes', 'hamstrings', 'back'],
    equipment: 'kettlebells',
    difficulty: 'beginner',
    instructions: '1. Stand with feet shoulder-width, KB between feet.\n2. Hinge at hips, grip KB handle.\n3. Drive through heels to stand.\n4. Keep back straight and core engaged.',
  },
  {
    id: 'kettlebell-windmill',
    name: 'Kettlebell Windmill',
    description: 'Core and shoulder stability exercise.',
    muscleGroups: ['core', 'shoulders'],
    equipment: 'kettlebells',
    difficulty: 'advanced',
    instructions: '1. Press KB overhead with one arm.\n2. Rotate feet 45 degrees away from KB.\n3. Hinge at hips, lowering free hand toward ground.\n4. Keep eyes on KB throughout.',
  },
  {
    id: 'kettlebell-figure-8',
    name: 'Kettlebell Figure 8',
    description: 'Dynamic core and coordination exercise.',
    muscleGroups: ['core', 'forearms'],
    equipment: 'kettlebells',
    difficulty: 'intermediate',
    instructions: '1. Stand wider than shoulder-width.\n2. Pass KB through legs from one hand to other.\n3. Create figure-8 pattern between legs.\n4. Keep chest up and core engaged.',
  },
  {
    id: 'kettlebell-halo',
    name: 'Kettlebell Halo',
    description: 'Shoulder mobility and warm-up exercise.',
    muscleGroups: ['shoulders', 'core'],
    equipment: 'kettlebells',
    difficulty: 'beginner',
    instructions: '1. Hold KB bottom-up at chest level.\n2. Circle KB around head in one direction.\n3. Keep head still and core tight.\n4. Switch directions after completing reps.',
  },
];

// Verify we have 50+ exercises
console.log(`Total exercises: ${exerciseSeedData.length}`);
